version: '2'

services:
  jenkins-master:
    build: infrastructure/jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-slave:
    restart: always
    build: infrastructure/jenkins-slave
    privileged: true
    volumes:
      - jenkins_slave_home:/var/jenkins_home
    environment:
      - JENKINS_URL=http://jenkins-master:8080 533549dc0e25b7af5fda8a9da7e034cea53c7bbc4a884c6068d24411a6ee1849 slave1
volumes:
  jenkins_home:
    driver: local
  jenkins_slave_home:
    driver: local
